### ISSUE TITLE
EOS Nation Ambassador + anything related to finance and strategy

### ISSUE THREAD

**Issue by DenisCarriere** [EOS-Nation/Ambassadors#2]
> EOS Nation`members.md` has been changed to Ambassadors (transferred on behalf of @lapapanite)

- [Papy Bakayoko ] Full Name
- [ Montreal Canada] Geographical Location
- [<script src="https://gist.github.com/lapapanite/746a9cd0bf8b40ac7f14bbe5396145f9.js"></script> ] Headshot image
- [Curious mind evolving in the finance industry as portfolio manager in an asset management firm. I Like to ski, get some shot at the basket or read during my spare time.  I had my aha moment the first time I read about the concept of smart contract, totally impressed by the level of disruption the blockchain technology could bring to the finance industry and to the overall organization of our society. 
If I was able to envision the disruptive potential of the technology, scalability and governance issues made me feel doubtful about the viability of the DLT until i came across the EOS white paper. Then all the pieces of the puzzle came together,  EOS is being built by an experienced team with a clear vision, solving the scalability and governance issues to harness the benefits of decentralization to secure the values that are dear to us liberty and property right.  
I'm here too give my contribution to this endeavor, increase the awareness about the blockchain, share the knowledge and help grow the community of developers on the platform] Bio (Description of yourself)

- [ Meetup organizer: I've read a lot about different blockchain protocols and grasped a good knowledge base to put forward the strong points of EOS relative to other blockchains  protocols and defend the vision chosen by EOS.
  Venture Cap:  Strong background in finance CFA charter holder, good experience and network we could leverage. I have been involved with different types of companies in various industries for instance the Star group at various level from first warrant financing as AMAYA gaming till LBO purchase of Pokerstar. good network within the financial industry in Montreal and Toronto] Proposed Role and why should we choose you?
- [ ] Social Media Accounts (Optional)
  - [ Layimoussa-moini Lapapanite] Facebook
  - [ lapapanite] Steemit
  - [Papa Mamadou Bakayoko ] LinkedIn
  - [ ] Twitter
  - [ ] GitHub
  - [LMMLPP ] Telegram

**Comment by DenisCarriere** [comment]
@lapapanite could you provide us any online content that you have published related to EOS/CryptoCurrencies/Blockchain industry.

I believe it would be very valuable to have someone that would be able to create content related to the Financial sector related to EOS and related markets.

We would like to book a video call with you which would allow us to discuss the role as an Ambassador with EOS Nation.

For private details, you can email us directly at info@eosnation.io or find one of our Admins on our public Telegram chat https://t.me/EOSNation

**Comment by lapapanite** [comment]
Hello Denis, 
Thank you the reply, just caught it, I'm not too frequent on GitHub. I wrote something on Medium as a support for a Panel I'm part of at Eastern Bloc which is planned for May. You can have a look here https://medium.com/@pmbakayoko/in-2017-the-start-ups-of-the-blockchain-industry-raised-several-times-more-money-through-the-c53ba5243781 

I'm currently writing something on EOS Cryptoeconomics and ETH to show how EOS is better fit to scale and will outpace ETH when main net goes live. Looking to write something on how EOS could be great for private companies, for that one I would need the help of someone who can write a short code in WASM - I code in other languages VB.net, Python but never interacted with a Blockchain too. also let me know if there is any subject.

For video conf Tomorrow 8PM will be fine otherwise Monday 8PM. or propose your time we can still video call with my phone.
Cheers!

**Comment by DenisCarriere** [comment]
Good day @lapapanite, sorry we've been disconnected for a while (14 days).

We've now moved our Ambassador applications over as a Google Forms.

https://docs.google.com/forms/d/e/1FAIpQLSdF7k6JA3zwUlswaY-24H1pfZnvMyY7uix3EmOEjIxmE80PrQ/viewform

If you could simply copy-paste some of your details from this GitHub issue over to that, someone will be able to reach out to you in the coming days to book a video call.

Looking forward in speaking with you.

**Comment by lapapanite** [comment]
Sounds Good! I Just posted the application. 
Looking forward!
